name: Docker Build and Push

on:
  push:
    branches:
      - 'main'

jobs:
  call-workflow-dockerhub-build-push:
    uses: NelsonDane/Custom-GitHub-Actions/.github/workflows/docker-registry-build-push.yml@e64ec758b6758d58955cab25a0e330f9bab380dd
    with:
      image_name: casinoclaim
      image_tag: latest
      should_push: ${{ github.ref_name == 'main' || startsWith(github.ref_name, 'main') }}
      platforms: linux/amd64
    secrets:
      DOCKER_REGISTRY_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}